#!/bin/bash
sink=pactl list sinks | grep -B 1 'State: RUNNING' | grep 'Sink #' | awk '{print $2}' | tr -d '#'
[[ $(pactl get-sink-volume $sink | grep -i 'volume' | awk '{gsub(/%/, "", $5); print $5}') -lt 60 ]] && pactl set-sink-volume $sink +10%
